### PR TITLE
Webapp Redesign

### LINKED ISSUE #83: Avoid tracking the user on Youtube from the frontpage
Even if one doesn't open the "watch intro video", there's a ton of queries done on YouTube... which ain't really cool, tracking-wise :-/

Maybe this should be on a separate page, or embedded in a way that doesn't query YT at each access to the homepage...

### PR DESCRIPTION
**Pull request by nlundquist**
- Componentized WebComponents based on lightweight libraries (lit-html & haunted)
- Redesigned to use new NRE Blog theme
- Increased modularization and reduced imperative code

Todo:
- Extract some styles into NRE Theme repo (non-blocking)

Closes https://github.com/nre-learning/antidote-web/issues/83

### CODE REVIEW

**Comment by Mierdin** [comment]
Sorry @nlundquist I introduced some changes to the old footer so that we could fix the link to the old, somewhat hostile ToU document, and point to the new one, and it caused conflicts with your work. Take a peek at https://github.com/nre-learning/antidote-web/pull/85/commits/c818fec6938a5b9366a9dec3223cb5cccf016648, I basically undid those changes but added the link to the new ToU doc to the updated document you made. Hopefully that works.

**Comment by Mierdin** [comment]
@nlundquist Oops, forgot this one was open when we talked last. I guess you'll just roll any additional changes into this PR. Please give a heads up when you're finished here.

**Comment by nlundquist** [comment]
Closed in favor of PR of sub-branch #85

**Comment by nlundquist** [comment]
Added in work from sub-branch rather than merging sub-branch into master. This is now ready for larger scale testing & eventual merging.

Of course this repo can no longer be tested by `make mock` since there's no WebSSH2 server to use to make the connection.

**Comment by Mierdin** [comment]
Thanks. Will open an issue to modify the makefile to be able to test with webssh2

**Pull request merged**
